### ISSUE TITLE
Check texts in Help/Info menus

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#6]
*Initially opened by gs108488 in [223@TIK](https://github.tik.uni-stuttgart.de/frankemx/damast/issues/223). History:*

**gs108488** Dec 16, 2021:

> All texts in info boxes when clicking on ? symbols in visualization need to be checked, especially in respect to publishing the life version.

**gs108488** Dec 16, 2021:

> I put this on halt until the state of the visualization for the life version is really final.

**Comment by mfranke93** [comment]
Side note about the info texts, because I just noticed @tutebatti's changes: The HTML `<h1>` tag should be reserved for page-level headings; that is, there is usually only one of these on a page. In my opinion, for the info textboxes, this is the title text at the top of the box (e.g., "Map View"). The headings *within* the info text should therefore start from `<h2>`. Example for the confidence view:

``` html
...
<h2>Contents</h2>
...
<h3>Levels of Confidence</h3>
...
...
<h2>Interaction</h2>
...
```

The current version for that view is inconsistent anyways. As I understood in our meeting this morning, @tutebatti's goal is to have two top-level items for each text, Contents and Interaction. At the moment, they are `<h1>` and `<h2>`, respectively.

**Comment by tutebatti** [comment]
Thank you for clarification. I suppose it was (probably accidently) `<h1>` somewhere in the original version and I took it from there. But anyways: I will make sure that `<h2>` is the top level everywhere and the overall structure is consistent top-down.

**Comment by mfranke93** [comment]
Another side not about style: Please put each sentence on a new line when editing HTML files. This won't affect representation, but makes reading the source and comparing diffs and pull requests way easier.

**Comment by tutebatti** [comment]
Will do. Thank you for this hint. However, when moving entire sections, this will not help a lot, will it?

**Comment by mfranke93** [comment]
Not a lot. But it is still helpful, especially since it is easier to see how long the section is (# line numbers).

**Comment by mfranke93** [comment]
One big issue when formatting is inconsistent is that it is harder to parse the structure. To solve this, we can do pure formatting commits from time to time. But these make it way harder to understand long-term changes to the source afterwards. Therefore, it is better to do it right from the start.

For the codebase of this project, that means one sentence per line for HTML and TeX, and a indent of two (not four) spaces.

**Comment by tutebatti** [comment]
Thank you for clarification. I'm sorry for any inconvenience.

**Comment by mfranke93** [comment]
No problem at all :)

**Comment by mfranke93** [comment]
FYI, I just merged `release/v1.0.4` (a6157e85ab54e0e37bc6c8a3ac956903a46d71ed) into the `feature/rephrase-info` branch, because it is a quite long-running branch and needs to stay up to date with what happens in the rest of the repo. That makes merging it back later easier. Also, I finished implementing #34 and need to update the info text accordingly.

**Comment by tutebatti** [comment]
Thank you. Please wait with commiting the updated info text. I am working on the info text of _Religion_ right now.

**Comment by mfranke93** [comment]
> wait with commiting 
That's not how this works, usually. I have already committed anyways, but I will not push and handle the merge locally as soon as you give me the go-ahead.

**Comment by tutebatti** [comment]
I am done with religion-hierarchy.html.

I am still not quite sure how I should have handled that on my local machine. So if there are changes on the same file in the remote repository while I am working on it locally, how can I pull the changes and merge locally before pushing again?

**Comment by mfranke93** [comment]
> I am still not quite sure how I should have handled that on my local machine. So if there are changes on the same file in the remote repository while I am working on it locally, how can I pull the changes and merge locally before pushing again?

The first step is to `git pull` (or `git fetch` first). Ideally, this is then possible without conflict, and you can just `git push` afterwards. In that case, the merge is done automatically. Even if both histories have changes to the same file, in most cases git can still do the merge automatically. In my experience, merge conflicts occur mostly if two histories have changes in the same line, or to the same characters.

In this case, there were changes that cannot be automatically merged. In that case, you would need to resolve them locally using `git mergetool`. For example, I usually use `vim` directly for this:
![image](https://user-images.githubusercontent.com/9373678/149941209-c830a692-46cd-444d-99bf-abc4effb42c7.png)

But I can also recommend [Meld](https://meldmerge.org/help/resolving-conflicts.html):
![image](https://user-images.githubusercontent.com/9373678/149942973-1638ef4d-49dc-4d2a-8113-f394c0b886d2.png)

I don't think this will happen often, but still it might be useful to know. And "waiting to commit" will never be a solution, because as soon as I would have pulled your changes, I would have had to resolve the conflicts anyways. The only "real" solution would have been to wait with *making* the changes until you were done, but then only one of us could work at a time, so it is not really feasible.

**Comment by tutebatti** [comment]
> And "waiting to commit" will never be a solution, because as soon as I would have pulled your changes, I would have had to resolve the conflicts anyways.

That is the point, and the point I hadn't thought about. Thanks again for clarification.

**Comment by tutebatti** [comment]
Sounds good to me. Also good for me to see what they actually look like as part of the visualization.

**Comment by mfranke93** [comment]
Regarding your [code comment](https://github.com/UniStuttgart-VISUS/damast/blob/e8d29975a34121e9f404a613b04d7624c229295f/dhimmis/vis/templates/vis/info/map.html#L129) regarding Geoman in the map info box: I would say yes, this is relevant, because users can refer to the Geoman documentation for more information on how to use the plugin.

**Comment by mfranke93** [comment]
@tutebatti I now released `v1.0.4`, and merged back the changes from there into the `feature/rephrase-info` branch. You might notice that there is now a tiny bit of `Jinja2` magic in the info text files. Generally, you can ignore those. However, it is now possible to add pictures (which will only appear in the [complete, connected documentation](https://www2.visus.uni-stuttgart.de/damast/docs/vis)) as well as links (see [here](https://github.com/UniStuttgart-VISUS/damast/blob/579c245deb5080450134cbb0a9eae38743589a10/dhimmis/vis/templates/vis/info/religion-hierarchy.html#L152) for an example). These links will point to the full documentation. So, there they can be used to scroll between sections, and in the info boxes they can be used to reference sections "outside" the text of that box (like, a reference to the settings pane from the religion view).

Feel free to reach out if you have any questions or suggestions! Also, we can now start writing the introduction of common vis/UI terms [here](https://github.com/UniStuttgart-VISUS/damast/blob/579c245deb5080450134cbb0a9eae38743589a10/dhimmis/docs/templates/docs/vis.html#L47).

**Comment by tutebatti** [comment]
Is there any html element/tag I should use for line breaks, if I do *not* want to use `<p>`? E.g., a break or typographical signal, that this is more than a period but less than a change in paragraph.

**Comment by mfranke93** [comment]
`<br />`

**Comment by tutebatti** [comment]
Thank you. It helps a lot to see now what everything looks like inside the visualization.

**Comment by tutebatti** [comment]
Update: The general rephrasing of the info texts is almost done, only #82 needs to be implemented.

There are two more things I will check *throughout* the texts:

1) Terminology: especially the distinction between "selection" and "filtering" (cf. #72); I would like to solve this by using "brushing" throughout with a (very) short explanation when used for the first time in each info text; also there can be a link to the "general section" in the documentation.

2) Formatting: this pertains to #62, #76 and #37.

From my perspective, @mfranke93 could already go over all info texts now to double-check for obvious error regarding explanations, terminology etc. from the point of view of visualization science etc., but since I will tackle the remaining issuesvery soon, we could also wait for that.

At any rate, after @mfranke93 has double-checked, I would have a colleague look at the visualization together with the info texts to have another "fresh look" at the whole thing.

Any suggestions regarding this procedure are welcome.

**Comment by tutebatti** [comment]
Thank you! I will look through all of your changes and comment, if necessary.

**Comment by tutebatti** [comment]
I just went over everything.

First, thank you for all the extra effort. I'm sorry that you had to correct a lot things back to what they might have been before. We should have agreed on a style guide before the whole procedure...

On the other hand, I am happy that content-wise, little has changed and my revised explanations seem to work.

**Comment by mfranke93** [comment]
Thanks for looking it over. I applied your suggestions where I did not have any reason for further discussion in 8f62c3f.

> We should have agreed on a style guide before the whole procedure...

That is always difficult to do before having seen what is actually there. Don't sweat it :) Besides, my original texts were probably not consistent either, as they were created at different points in time.

> On the other hand, I am happy that content-wise, little has changed and my revised explanations seem to work.

Yes. Thanks for taking the time to restructure and reformulate, and to clear things up. I have to note, though, that my focus was not on overall content. I trust your judgment there on what needs to be explained, and how. I only changed some use of terminology, and removed two statements ([here](https://github.com/UniStuttgart-VISUS/damast/commit/506404fce32ce9f7b11dd721a45caf2b24ba8faa#r66716875) and [here](https://github.com/UniStuttgart-VISUS/damast/commit/31fa9c85ad887b94c1c5f74f06343144c0740572#r66717547)) that did not reflect the actual functionality.

I would say that, as soon as the general introduction to UI and InfoVis terms is completed, this could be merged, right?

**Comment by tutebatti** [comment]
> I would say that, as soon as the general introduction to UI and InfoVis terms is completed, this could be merged, right?

If possible, I would prefer an earlier merge of just the info texts, or rather have the updated texts on the production server, so Dorothea can have a look as well, in the context of the visualization. Is that possible?

**Comment by mfranke93** [comment]
It would be a text-only release in that case, but yes, it would be possible. The other option is to deploy the current state of this branch, as-is, to the testing server, and to give you all a user/password to look at it there. I am fine with either, although using the testing server is less work for me.

**Comment by tutebatti** [comment]
We will use the testing server then. Please send individual credentials to Dorothea, Jörn and me. Thank you!

**Comment by tutebatti** [comment]
Update: Dorothea will go through the info texts in the coming days. After discussing her suggestions and possibly altering the text, there will be one final correction by an English native speaker.

**Comment by tutebatti** [comment]
Again, update: I recently pushed some commits regarding the info texts as well as the introduction to visualization terminology etc. Would you, @mfranke93, please have a look, if this is fine contentwise so we can forward it to the native speaker?

**Comment by tutebatti** [comment]
To pick this up again: (1) Can the text go to the native speaker in its current form? (2) How can we easiest create a google or MS Word document to provide that to them? Can you deploy the feature/rephrase-info branch to the testing server so I can copy paste the documentation?

**Comment by mfranke93** [comment]
Done

**Comment by tutebatti** [comment]
Thank you.

> Can you deploy the feature/rephrase-info branch to the testing server so I can copy paste the documentation?

This question/inquiry is open, but could wait until April no problem.

**Comment by mfranke93** [comment]
Sorry, maybe "done" was not specific enough :D Done deploying that to the testing server. But yes, in my opinion this can now also be proofread.
________________________________________

**Comment by tutebatti** [comment]
Great, thank you so much!

**Comment by tutebatti** [comment]
I have just added the few remaining comments by the native speaker. We can wrap this up, I guess.
